### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by lfittl** [papertrail/go-tail#7]
Hi - It seems this project unfortunately has no LICENSE file, or any other declaration of how it is licensed.

@snorecone Since you seem to be the primary author - was this intentional, or just oversight?

I'd love to use this library, but can't without the license being clear - appreciate it!

**Comment by snorecone** [comment]
@lfittl just oversight, thanks for the report!

**Comment by lfittl** [comment]
@snorecone Yay, thanks for fixing!

And great work on the library btw - I love how small and contained it is, compared to the hpcloud tail library :)
